#!/bin/bash
TARGET_FILE="$HOME/.zshrc"
if ! grep -q "BuckyVPN" "$TARGET_FILE"; then
    echo 'export PATH="$PATH:/Applications/BuckyVPN.app/Contents/MacOS"' >> "$TARGET_FILE"
fi

PLIST_PATH="/Library/LaunchDaemons/com.bucky.vpn.plist"
cp "com.bucky.vpn.plist" "$PLIST_PATH"

chown root:wheel "$PLIST_PATH"
chmod 644 "$PLIST_PATH"

sudo launchctl bootout system/com.bucky.vpn
launchctl load -w "$PLIST_PATH"
